name: Release - Python Package

on:
  release:
    types: [published]

jobs:
  build-n-release:
    name: Build wheels on ubuntu-latest
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Build package
        run: |
          uv pip install -e .[dev]
          python -m build --wheel
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
